#!/usr/bin/env bash

if [[ -e $1 ]] ; then
    echo "Usage: "
    echo "       querymvn <group>:<artifact>:<type>:<version>"
    echo "       querymvn <url>"
    echo "  example: querymvn org.apache.commons:commons-lang3:jar:3.8.1"
    exit 1
fi

BASEURL=$(grep -E "<url>" ~/.m2/settings.xml | head -n 1 | sed -r -e 's#.*<url>(.*)</url>.*#\1#')
USERNAME=$(grep -E "<username>" ~/.m2/settings.xml | head -n 1 | sed -r -e 's#.*<username>(.*)</username>.*#\1#')
PASSWORD=$(grep -E "<password>" ~/.m2/settings.xml | head -n 1 | sed -r -e 's#.*<password>(.*)</password>.*#\1#')

if [[ ${1%//*} == "https:" ]] || [[ ${1%//*} == "http:" ]] ; then
    URL="$1"
    FILENAME="${URL##*/}"
else
    PKG="$1"
    GROUP=$(echo -n "$PKG" | cut -d ':' -f 1)
    ARTIFACT=$(echo -n "$PKG" | cut -d ':' -f 2)
    TYPE=$(echo -n "$PKG" | cut -d ':' -f 3)
    VERSION=$(echo -n "$PKG" | cut -d ':' -f 4)
    FILENAME="$ARTIFACT-$VERSION.$TYPE"
    PKGPATH="$(echo -n "$GROUP" | sed -r -e 's#\.#/#g')/$ARTIFACT/$VERSION/$FILENAME"
    URL="$BASEURL/$PKGPATH"
fi

if command -v bat >/dev/null 2>&1 ; then
    FORMATTER="bat"
else
    FORMATTER="cat"
fi

if command -v jq >/dev/null 2>&1 ; then
    JSON_FORMATTER="jq ."
else
    JSON_FORMATTER="$FORMATTER"
fi


rm "$FILENAME"

curl -u "$USERNAME:$PASSWORD" --basic -LO -v "$URL"

if [[ -e $FILENAME ]] && (file "$FILENAME" | grep -E -q -i 'JSON') ; then
    $JSON_FORMATTER <"$FILENAME"
elif [[ -e $FILENAME ]] && (file "$FILENAME" | grep -E -q -i 'text') ; then
    $FORMATTER "$FILENAME"
fi
